[build]
    publish = "site"
    functions = "functions"
[functions]
    [functions.hello]
        included_files = ["templates/*.hbs"]
[[redirects]]
    from = "/"
    to = "/.netlify/functions/"
    status = 200