[build]
    publish = "public"
    functions = "src"
[functions]
        included_files = ["templates/*.hbs"]
[[redirects]]
    from = "/*"
    to = "/.netlify/functions/"
    status = 200
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
[[edge_functions]]
  path = "/*"
  function = "common"